worker_processes auto;

events { worker_connections 1024; }

http {
    include /etc/nginx/mime.types;
    default_type  application/octet-stream;
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;

    server {
        listen 8888;
        server_name _;

         # API requests (with rate limiting)
        location / {
            limit_req zone=api_limit burst=20 nodelay;
            proxy_pass http://backend:4000;   #to send the req to backend service
            proxy_connect_timeout 5s;
            proxy_read_timeout 60s;
            proxy_buffering off;
        }

        # Serve all HLS files
        location /hls/ {    # ends with a slash so it treats it as a search for dir
            alias /hls/;
            add_header Cache-Control no-cache;
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Headers *;
            add_header Access-Control-Allow-Methods "GET, OPTIONS";
            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }
        }
    }
}

